Repository CelianHache/Arbre_Genealogique, pull requests merged in 2025-01, with the labels that each got.

#19 Generic binary tree
  .gitignore
  src/arbre_bin.adb
  src/arbre_bin.ads
  src/main.adb
Labels: feature, test

#20 Minimal tree
  .gitignore
  src/arbre_bin.adb
  src/arbre_genealog.adb
  src/arbre_genealog.ads
  src/main.adb
  src/personne.adb
  src/personne.ads
  src/tests.adb
Labels: feature, test

#21 Parent tree
  src/arbre_bin.adb
  src/arbre_bin.ads
  src/arbre_genealog.adb
  src/arbre_genealog.ads
  src/main.adb
  src/tests.adb
Labels: feature, test

#23 [Count_Ancestor] add function count_ancestors
  src/arbre_genealog.adb
  src/arbre_genealog.ads
  src/tests.adb
Labels: feature, test

#26 [Remove_Code_Duplication] Fix code duplication
  src/tests.adb
Labels: Fix

#29 Number of parents
  src/arbre_genealog.adb
  src/arbre_genealog.ads
  src/tests.adb
Labels: feature, test

#30 [Display_Tree_From_Node] Fix Get Node By Id and Add Display_Tree_From…
  src/arbre_bin.adb
  src/arbre_genealog.adb
  src/arbre_genealog.ads
Labels: feature

#34 [Remove_Node] Add remove node function
  src/arbre_bin.adb
  src/arbre_bin.ads
  src/arbre_genealog.adb
  src/arbre_genealog.ads
  src/personne.adb
  src/personne.ads
  src/tests.adb
Labels: feature, test

#35 [Fix_Remove_Node] Fix pointer access lost during merge
  src/personne.adb
Labels: Fix

#36 [Spec_Personne] add spec to personne package
  src/personne.adb
  src/personne.ads
Labels: documentation

#37 Menu interactif
  src/main.adb
Labels: documentation, feature

#38 Spec genealog
  src/arbre_genealog.adb
  src/arbre_genealog.ads
Labels: documentation

#39 Spec arbre bin
  src/arbre_bin.adb
  src/arbre_bin.ads
Labels: documentation
